name: Python API
on: [push, pull_request]

env:
  CIBW_BEFORE_BUILD: bash {project}/bindings/python/tools/prepare_build_environment.sh
  CIBW_TEST_COMMAND: pytest {project}/bindings/python/test/test.py
  CIBW_TEST_REQUIRES: pytest
  CIBW_SKIP: pp*
  CI: true

jobs:
  build:
    name: Building and testing on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python_version }}
      uses: actions/setup-python@v1
      with:
        python-version: 3.7

    - name: Install Visual C++ for Python 2.7
      if: startsWith(matrix.os, 'windows')
      run: |
        choco install vcpython27 -f -y

    - name: Build sdist
      if: startsWith(matrix.os, 'ubuntu')
      run: |
        python -m pip install pybind11==2.4.3
        python bindings/python/setup.py sdist --dist-dir bindings/python/dist

    - name: Build and test wheels
      run: |
        # Switch to cibuildwheel from PyPI after https://github.com/joerick/cibuildwheel/pull/295 is merged
        python -m pip install https://github.com/filips123/cibuildwheel/archive/2702767a17efa0bee3ac90b1f6b8561e01eb1538.zip
        python -m cibuildwheel . bindings/python --output-dir bindings/python/dist

    - name: Upload artifacts to storage
      uses: actions/upload-artifact@v1
      with:
        name: wheels
        path: bindings/python/dist

  publish:
    name: Publishing package to PyPI
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags')
    needs: [build]

    - name: Download artifacts from storage
      uses: actions/download-artifact@v1
      with:
        name: wheels
        path: dist

    - name: Publish artifacts to PyPI
      uses: pypa/gh-action-pypi-publish@master
      with:
        user: __token__
        password: ${{ secrets.pypi_password }}
        packages_dir: dist
